laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('perfil', 'PerfilController@index')->name('perfil');
    Route::get('projetos/{projetos_categoria?}', 'ProjetosController@index')->name('projetos');
    Route::get('projetos/{projetos_categoria}/{projeto}', 'ProjetosController@show')->name('projetos.show');
    Route::get('produtos/{produtos_categoria?}', 'ProdutosController@index')->name('produtos');
    Route::get('publicacoes', 'PublicacoesController@index')->name('publicacoes');
    Route::get('publicacoes/{publicacao}', 'PublicacoesController@show')->name('publicacoes.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@envio')->name('contato.envio');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::resource('mobiliario/abertura', 'MobiliarioAberturaController', ['only' => ['index', 'update']]);
        Route::get('mobiliario/{mobiliario}/imagens/clear', [
            'as'   => 'painel.mobiliario.imagens.clear',
            'uses' => 'MobiliarioImagensController@clear'
        ]);
        Route::resource('mobiliario.imagens', 'MobiliarioImagensController');
        Route::resource('mobiliario', 'MobiliarioController');
		Route::resource('divisorias/abertura', 'DivisoriasAberturaController', ['only' => ['index', 'update']]);
		Route::resource('divisorias', 'DivisoriasController');
		Route::resource('aromas', 'AromasController', ['only' => ['index', 'update']]);
        Route::resource('projetos/categorias', 'ProjetosCategoriasController');
        Route::resource('projetos', 'ProjetosController');
        Route::get('projetos/{projetos}/imagens/clear', [
            'as'   => 'painel.projetos.imagens.clear',
            'uses' => 'ProjetosImagensController@clear'
        ]);
        Route::resource('projetos.imagens', 'ProjetosImagensController');
		Route::resource('publicacoes', 'PublicacoesController');
        Route::get('publicacoes/{publicacoes}/imagens/clear', [
            'as'   => 'painel.publicacoes.imagens.clear',
            'uses' => 'PublicacoesImagensController@clear'
        ]);
        Route::resource('publicacoes.imagens', 'PublicacoesImagensController');
		Route::resource('perfil', 'PerfilController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Models/Mobiliario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Mobiliario extends Model
{
    protected $table = 'mobiliario';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('ordem', 'ASC')->orderBy('imagem', 'ASC');
    }

    public function imagens()
    {
        return $this->hasMany('App\Models\MobiliarioImagem', 'mobiliario_id')->ordenados();
    }
}

laravel/app/Http/Controllers/Painel/AromasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AromasRequest;
use App\Http\Controllers\Controller;

use App\Models\Aromas;
use App\Helpers\CropImage;

class AromasController extends Controller
{
    private $image_config = [
        'width'  => 470,
        'height' => null,
        'path'   => 'assets/img/aromas/'
    ];

    public function index()
    {
        $registro = Aromas::first();

        return view('painel.aromas.edit', compact('registro'));
    }

    public function update(AromasRequest $request, Aromas $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            }

            $registro->update($input);

            return redirect()->route('painel.aromas.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;
use App\Helpers\CropImage;

class BannersController extends Controller
{
    private $image_config = [
        'width'  => 1980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/banners/'
    ];

    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {
            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);
        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            }

            $registro->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }

    public function destroy(Banner $registro)
    {
        try {
            $registro->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DivisoriasAberturaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DivisoriasAberturaRequest;
use App\Http\Controllers\Controller;

use App\Models\DivisoriasAbertura;
use App\Helpers\CropImage;

class DivisoriasAberturaController extends Controller
{
    private $image_config = [
        'width'  => 230,
        'height' => null,
        'path'   => 'assets/img/divisorias/abertura/'
    ];

    public function index()
    {
        $registro = DivisoriasAbertura::first();

        return view('painel.divisorias.abertura.edit', compact('registro'));
    }

    public function update(DivisoriasAberturaRequest $request, DivisoriasAbertura $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            }

            $registro->update($input);

            return redirect()->route('painel.divisorias.abertura.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/DivisoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DivisoriasRequest;
use App\Http\Controllers\Controller;

use App\Models\Divisoria;
use App\Helpers\CropImage;

class DivisoriasController extends Controller
{
    private $image_config = [
        [
            'width'  => 230,
            'height' => 230,
            'path'   => 'assets/img/divisorias/thumbs/'
        ],
        [
            'width'  => 680,
            'height' => null,
            'upsize' => true,
            'path'   => 'assets/img/divisorias/'
        ]
    ];

    public function index()
    {
        $registros = Divisoria::ordenados()->get();

        return view('painel.divisorias.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.divisorias.create');
    }

    public function store(DivisoriasRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $imagem = Divisoria::create($input);

            $view = view('painel.divisorias.imagem', compact('imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function show(Divisoria $registro)
    {
        return $registro;
    }

    public function destroy(Divisoria $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.divisorias.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/MobiliarioAberturaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\MobiliarioAberturaRequest;
use App\Http\Controllers\Controller;

use App\Models\MobiliarioAbertura;
use App\Helpers\CropImage;

class MobiliarioAberturaController extends Controller
{
    private $image_config = [
        'width'  => 230,
        'height' => null,
        'path'   => 'assets/img/mobiliario/abertura/'
    ];

    public function index()
    {
        $registro = MobiliarioAbertura::first();

        return view('painel.mobiliario.abertura.edit', compact('registro'));
    }

    public function update(MobiliarioAberturaRequest $request, MobiliarioAbertura $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            }

            $registro->update($input);

            return redirect()->route('painel.mobiliario.abertura.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/MobiliarioController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\MobiliarioRequest;
use App\Http\Controllers\Controller;

use App\Models\Mobiliario;
use App\Helpers\CropImage;

class MobiliarioController extends Controller
{
    private $image_config = [
        'width'  => 230,
        'height' => 230,
        'path'   => 'assets/img/mobiliario/thumbs/'
    ];

    public function index()
    {
        $registros = Mobiliario::ordenados()->get();

        return view('painel.mobiliario.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.mobiliario.create');
    }

    public function store(MobiliarioRequest $request)
    {
        try {
            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Mobiliario::create($input);
            return redirect()->route('painel.mobiliario.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);
        }
    }

    public function edit(Mobiliario $registro)
    {
        return view('painel.mobiliario.edit', compact('registro'));
    }

    public function update(MobiliarioRequest $request, Mobiliario $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            }

            $registro->update($input);
            return redirect()->route('painel.mobiliario.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }

    public function destroy(Mobiliario $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.mobiliario.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class PainelController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i + 1));
        }

        return json_encode($data);
    }

}

laravel/app/Http/Controllers/Painel/PerfilController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\PerfilRequest;
use App\Http\Controllers\Controller;

use App\Models\Perfil;
use App\Helpers\CropImage;

class PerfilController extends Controller
{
    private $image_config = [
        'width'  => 360,
        'height' => null,
        'path'   => 'assets/img/perfil/'
    ];

    public function index()
    {
        $registro = Perfil::first();

        return view('painel.perfil.edit', compact('registro'));
    }

    public function update(PerfilRequest $request, Perfil $registro)
    {
        try {
            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) {
                $input['imagem'] = CropImage::make('imagem', $this->image_config);
            }

            $registro->update($input);

            return redirect()->route('painel.perfil.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/mobiliario/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Mobiliário /</small> Adicionar Mobiliário</h2>
    </legend>

    {!! Form::open(['route' => 'painel.mobiliario.store', 'files' => true]) !!}

        @include('painel.mobiliario.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/mobiliario/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Mobiliário /</small> Editar Mobiliário</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.mobiliario.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.mobiliario.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/mobiliario/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('imagem', 'Capa') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/mobiliario/thumbs/'.$registro->imagem) }}" style="display:block; margin-bottom: 10px; width: 100%; max-width: 230px;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.banners.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/mobiliario/index.blade.php
            {!! Form::open(['route' => ['painel.mobiliario.store'], 'files' => true, 'class' => 'clearfix pull-right']) !!}
                <div class="btn-group pull-right">
                    <a href="{{ route('painel.mobiliario.abertura.index') }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-align-left" style="margin-right:10px;"></span>Editar Abertura</a>
                    <span class="btn btn-success btn-sm" style="position:relative;overflow:hidden">
                        <span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>
                        Adicionar Imagens
                        <input id="images-upload" type="file" name="imagem" id="imagem" multiple style="position:absolute;top:0;right:0;opacity:0;font-size:200px;cursor:pointer;">
                    </span>
                </div>
            {!! Form::close() !!}
        </h2>
    </legend>

@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Mobiliário
            <div class="btn-group pull-right">
                <a href="{{ route('painel.mobiliario.abertura.index') }}" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-align-left" style="margin-right:10px;"></span>Editar Abertura</a>
                <a href="{{ route('painel.mobiliario.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Mobiliário</a>
            </div>
        </h2>
    </legend>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="mobiliario">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th>Imagem de capa</th>
                <th>Imagens</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->titulo }}</td>
                <td><img src="{{ url('assets/img/mobiliario/thumbs/'.$registro->imagem) }}" alt="" style="width:100%;max-width:100px;height:auto;"></td>
                <td><a href="{{ route('painel.mobiliario.imagens.index', $registro->id) }}" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Gerenciar
                </a></td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.mobiliario.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.mobiliario.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>


    @endif

@endsection